services:
  web:
    build: .
    command: gunicorn -c gunicorn.conf.py config.wsgi:application
    volumes: []
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    restart: unless-stopped

  worker:
    build: .
    command: celery -A config worker --loglevel=info --concurrency=4
    volumes: []
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    restart: unless-stopped

  beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes: []
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    restart: unless-stopped

  db:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped

volumes:
  postgres_data:
