# Generated by Django 5.0.9 on 2026-07-25 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('era_label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('google_maps_link', models.CharField(blank=True, max_length=500, null=True)),
                ('pin_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pin_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pin_place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_experiences', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cities.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='experiences.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', through='experiences.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('panorama_360', '360 panorama'), ('still_image', 'Still image'), ('thumbnail', 'Thumbnail'), ('3d_model', '3D model')], max_length=20)),
                ('storage_path', models.CharField(max_length=500)),
                ('signed_url_expiry_seconds', models.PositiveIntegerField(default=900)),
                ('source_type', models.CharField(choices=[('ai_generated', 'AI generated'), ('archival', 'Archival'), ('partner_upload', 'Partner upload')], max_length=20)),
                ('attribution_text', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='experiences.experience')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'experience'), name='unique_user_experience_favorite'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['city', 'year'], name='experiences_city_id_634c30_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['status'], name='experiences_status_306c11_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['experience', 'type'], name='experiences_experie_d6897f_idx'),
        ),
    ]
