# Generated by Django 5.0.9 on 2026-07-25 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narrative_script', models.TextField()),
                ('description', models.TextField()),
                ('audio_narration_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_prompt_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=300)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_content', to='experiences.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('job_type', models.CharField(choices=[('story_text', 'Story text'), ('image', 'Image'), ('full_bundle', 'Full bundle')], default='story_text', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='experiences.experience')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['experience', 'status'], name='ai_generati_experie_65d274_idx')],
            },
        ),
    ]
