# Generated by Django 5.0.9 on 2026-07-25 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published')], default='draft', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='cities.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('stop_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('stop_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stops', to='experiences.experience')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='journeys.journey')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='journeystop',
            constraint=models.UniqueConstraint(fields=('journey', 'sequence_order'), name='unique_journey_sequence_order'),
        ),
    ]
